### ISSUE TITLE
Is there new version of XML specification?

### ISSUE THREAD

**Issue by destogl** [FreeOpcUa/python-opcua#164]
Hello,

working on Events and playing with references, I realised that Text-Specification and XML-Specification in this respository are not 100% overlapping. One place I found difference is that  in XML-Spec `AlwaysGeneratesEvent` Reference type is a sub-type of `NonHierarchicalReferences` and Text-spec part 3, page 56, section 7.17 says:

> The _AlwaysGenratesEvent ReferenceType_ is a concrete _ReferenceType_ and can be used directly. It is a subtype of _GeneratesEvent_.

There are possibly more differences. I don't know where to get XML-Spec, but the question is is there newer one with updates?

Currently this is not an issue, but it could be in the future...

**Comment by oroulet** [comment]
There are many contradictions and errors in spec. In addition some features in spec do not make sense and there are many redundancy which are really not necessary.... so far from perfect....
I created that bug a few years ago, maybe you can add this to it: https://github.com/FreeOpcUa/freeopcua/issues/120 . But maybe some of these errors have been fixed in 1.0.3
