### ISSUE TITLE
ModifyMonitoredItemResponse broken?

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/python-opcua#175]
Wireshark says we send a malformed packet in response to an ModifyMonitoredItemRequest for event subscription.
This is not sure we have an issue, wireshark is sometime wrong and our code is autogenerated and is usually correct.

**Comment by destogl** [comment]
I will try to subscribe on events from unifiedautomation SDK server so we will see...

**Comment by destogl** [comment]
How do you get ModifyMonitoredItemRequest?

**Comment by oroulet** [comment]
to get a modify monitored item requtes you need to modify the subscription by clicking on attributes of subscribed objects in event view

**Comment by Johen8** [comment]
Yeah, I think it is broken. When using UaExpert to connect to a server I get this message when trying to Modify a Monitored Item:
![erro_uaexpert](https://cloud.githubusercontent.com/assets/13229026/15177291/8b8b12d6-176f-11e6-9dc2-29cb9a51b93e.PNG)

Then I implemented on the client side a function to Modify Monitored Items (I couldn't find one, at least) and I get the same message when trying to use it:
`[MonitoredItemModifyResult(StatusCode:StatusCode(Good), RevisedSamplingInterval:0.0, RevisedQueueSize:1084178432, FilterResult:None)]`

After this, I tried to use the same function with the UAF server and I got the following message, using the same parameters and function from the client:
`[MonitoredItemModifyResult(StatusCode:StatusCode(Good), RevisedSamplingInterval:5000.0, RevisedQueueSize:1, FilterResult:None)]`

So, I guess the problem is in the server.

(I couldn't get my modify monitored item to function properly after the modification, I get this error:
`WARNING:opcua.common.subscription:Received a notification for unknown handle: 202`
If anyone could help me, I'd appreciate it)
